name: "Build"
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: "Install dependencies"
        uses: bun install

      - name: "Build and Zip"
        run: |
          bun run zip
          bun run zip:firefox

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: .output/*.zip
          if-no-files-found: error
